package com.noxis.domain.enum

enum class NationalFoodsType {
    RUSSIAN_AND_SOVIET_FOOD,
    UKRAINIAN_FOOD,
    BELARUSIAN_FOOD,
    MOLDAVIAN_FOOD,
    TRANS_CAUCASIAN_FOOD,
    KAZAKH_AND_KYRGYZ_FOOD,
    CENTRAL_ASIAN_FOOD,
    BALTIC_FOOD,
    FINNO_UGRIC_PEOPLES_FOOD,
    MONGOLIAN_FOOD,
    JEWISH_FOOD,
}
